qojulia/QuantumOpticsBase.jl

- src/sortedindices.jl
Some of the commits are gratuitous style choices but it is much faster
Master
```julia
julia> indices = [3, [4,5]]
2-element Array{Any,1}:
3      
[4, 5]
julia> @btime QuantumOpticsBase.check_embed_indices($indices)
1.401 μs (26 allocations: 1.95 KiB)
```
This PR
```julia
julia> @btime QuantumOpticsBase.check_embed_indices($indices);
505.733 ns (15 allocations: 848 bytes)
```
> Simpler and faster checking for embed indices

- src/operators_dense.jl
- src/operators_lazysum.jl
- src/operators_lazytensor.jl
- src/states.jl
- test/test_operators_dense.jl
- test/test_operators_lazysum.jl
```Julia
using LinearAlgebra
julia> normalize!(rand(5))
5-element Array{Float64,1}:
0.6110615634304324 
0.5571396063270291 
0.5393678465871397 
0.1017128598624379 
0.12221311290640892
```
but not in QuantumOptics...
> add return value to normalize!

- Project.toml
- src/QuantumOpticsBase.jl
- src/metrics.jl
- test/test_metrics.jl
only for integer \alpha.
For non-integer we should add the exponential of non-integer operators, which is easy, but the algorithm in base is extremely unstable for low rank so I'd rather think a bit more about it.
> Renyi entropy

- src/fock.jl
- src/printing.jl
- src/transformations.jl
- test/test_fock.jl
- test/test_transformations.jl
The `transform` methods for transforming back and forth between `FockBasis` and `PositionBasis` still need to be adapted for offsets.
> Implement offset in FockBasis

- src/QuantumOpticsBase.jl
- src/phasespace.jl
It would be useful for other packages to be able to extend functions of QuantumOptics without depending on QuantumOptics.jl itself. I added to QuantumOpticsBase.jl declarations of phase space functions: `qfunc`, `wigner`, `coherentspinstate`, `qfuncsu2`, `wignersu2`.
I especially needed `wigner` for a package I am developing, but also the other functions may be useful to others. I made changes also to QuantumOptics.jl to accommodate this. 
I hope this can be useful.
> Phase space functions declaration

- src/metrics.jl
The documentation doesn't fit the code; which implements: https://en.wikipedia.org/wiki/Negativity_(quantum_mechanics)
> Fix documentation of `negativity`

- src/fock.jl
- src/states.jl
I initiated to apply the changes as discussed in #24. Before completing I think we should review the changes I made so far. I think there are some options also for the docs. The changes I made in `fock.jl` for the operators are what I am used to. I can modify, if you consider to be better another way.
> Added typed construtors for operators FockBasis

- src/operators_dense.jl
- src/operators_lazytensor.jl
- test/test_abstractdata.jl
- test/test_operators_lazytensor.jl
- test/test_printing.jl
This is actually a breaking change, since `LazyTensor` now requires the `indices` and `operators` to be sorted before construction. Previously if the arguments were unsorted, it was resorted in the constructor. Problem is, that causes type instabilities. I've never really encountered a case where unsorted arguments were important, so I'm inclined to just break it.
@amilsted you raised this issue in gitter, does that PR solve the inference problem for your use-case? Any other comments?
> Type-stable constructor for LazyTensor

- src/spin.jl
Suggesting a very simple change to a SpinBasis assertion to allow for spin-0. My use case has a composite system with a dynamically changing spin number, and the current workaround in the case where the spin number goes to zero is to change the definition of the composite basis to drop the SpinBasis entirely, which seems awkward as it leaves no trace that the composite system includes a spin.
This seems like a useful change for any use case that deals with an arbitrary spin number.
The standard state definitions and basic operators seem to work as expected when operating on SpinBasis(0).
> minor edit to SpinBasis

- src/operators_lazysum.jl
- src/operators_lazytensor.jl
- test/test_operators_lazysum.jl
- test/test_operators_lazytensor.jl
Reduce compile time of some lazy op arithmetic ops.
For example
```
ls = LazySum(b, b)
op = LazySum(randoperator(b))
@time for _ in 1:N  # compilation time scales with N
ls += op  # every `+` will require compilation, as the first argument changes type each iteration
end
```
> Faster lazy ops

- .github/workflows/ci-jet.yml
- Project.toml
- src/QuantumOpticsBase.jl
- src/manybody.jl
- src/operators.jl
- src/operators_dense.jl
- src/operators_lazysum.jl
- src/operators_lazytensor.jl
- src/sparsematrix.jl
- src/spinors.jl
- src/states.jl
- src/superoperators.jl
- test/runtests.jl
- test/test_aqua.jl
- test/test_jet.jl
Edit: this PR now completely integrates Aqua and JET static analysis in the test framework and fixes various (minor) issues detected by these tools.
~~This PR is not particularly useful on its own, but it makes it easier to start using Aqua and JET for static analysis. JET in particular is a great way to find bugs.~~
- [Aqua](https://github.com/JuliaTesting/Aqua.jl) is just for sanity checks. It did uncover a large number of method ambiguities, but some of them are unimportant. I have not tried to fix them for now and have just marked the test as broken.
- Aqua also complained about exporting symbols that are not actually defined. It seems they were used for documenting. I turned them into comments.
- JET found a ton of issues, but many of them are false positives. JET can be configured …
> add JET and Aqua static analysis tests

- .github/workflows/invalidations.yml
Recently I have seen a lot of the ecosystem, in particular SciML, using this invalidations checker to make sure they do not make import time and time-to-first-execution slower. Basically, it checks whether a PR introduces new invalidations as detected by SnoopCompile. https://github.com/julia-actions/julia-invalidations
I am interested in working on improving import times for this part of the ecosystem, and I think this type of CI improvements are a good second step (after the addition of Aqua and JET checks).
I have been using this for QuantumClifford.jl for quite a while.
> add an invalidations flagger to CI

- src/operators_lazytensor.jl
- test/test_aqua.jl
- test/test_operators_lazytensor.jl
If, for example, we are acting on CuArrays, we don't want intermediate results to be Vector. In these cases, just do not use the cache.
> LazyTensor: Do not assume intermediates should be Vectors

- src/operators.jl
- src/operators_dense.jl
- src/operators_lazytensor.jl
- test/test_operators.jl
- test/test_operators_lazytensor.jl
Following suggestion from @amilsted regarding https://github.com/qojulia/QuantumOptics.jl/issues/352
`shape`, `strides_j` and `strides_k` in `_gemm_puresparse` function are implemented as `Tuple` to reduce allocations.
> Reduce allocations for multipling LazyTensor of sparse and dense

- src/operators_dense.jl
- test/test_operators_lazysum.jl
Product of an Operator with an `AbstractMatrix` data and an `AbstractOperator` (`LazySum`) fails on;
https://github.com/qojulia/QuantumOpticsBase.jl/blob/2506d0da922999c2a7c0d28c340caf1b769cffe6/src/operators_dense.jl#L97
trying to build an Operator with data that is AbstractMatrix; e.g., `Hermition` or `Adjoint`.
As @amilsted suggested, using `parent` a few times to strip the data to a concrete type before allocating.
Also promoting the element type to account for `Operators` with `Real` data.
> Mul adjoint and lazy sum

- src/operators.jl
- src/operators_lazytensor.jl
Means we don't have to drop support for older Julia.
> Don't use lazy strings

- src/operators_lazysum.jl
- src/states.jl
- test/test_operators_lazysum.jl
Changed `eltype` for `LazySum` so it won't fail on an empty operator due to reducing over empty list.
Also added dim check for multiplication with empty `LazySum`.
Such that `LazySum(NLevelBasis(1),NLevelBasis(1)) * Ket(NLevelBasis(8), ... )` would fail with `DimensionMismatch`.
> Fix for multiplication of LazySum with no elements

- src/metrics.jl
- test/test_metrics.jl
fixed bug reported in #97 
the `ptranspose(rho::DenseOpType{B,B}, indices::Union{Vector{Int},Tuple{Vararg{Int}}})` method is added to support multi-index subsystems, and the original single-index method `ptranspose(rho::DenseOpType{B,B}, index::Int=1)` is kept for compatibility, but implemented as a special case using the multi-index version.
tests dedicated to the two methods are added.
> Fix bug in ptranspose and added corresponding tests

- Project.toml
- src/operators_dense.jl
- test/test_operators.jl
> Base.convert(::Type{Operator}, ::Operator)

- docs/src/api.md
- src/operators_lazyproduct.jl
- src/operators_sparse.jl
Time-dependent operator stuff. And get rid of a newline.
> Doc additions and a fix

- Project.toml
- src/manybody.jl
Performance optimizations:
- Setting an sparse matrix like `mat[i, j] = k` is extremely slow and unoptimal when done in a loop. It can be avoided by creating three separate lists for values and indices and calling `sparse(is, js, vs, size1, size2)` in the end.
- Allocating new arrays or copying existing ones causes significant slowdown. The new `coefficient` function does not allocate new arrays (or copy old ones) and accepts any iterable as indices - even single number values (they are iterable, too!).
Combined together this yields a 300x performance boost (23s -> 75ms for a full boson basis with 2 particles on 36 modes) for the `manybodyoperator` function.
Still, this is nearly not enough for large systems (for example, when there are 3 particles, `manybodypoerator` runs for 12 …
> [WIP] Improve generation performance in manybody.jl

- src/fock.jl
- test/test_fock.jl
I recently got bitten by this subtle bug caused when naively calling `displace_analytical(FockBasis(30), 5)` which then causes `alpha^(n - m)` to overflow for `n-m>27` since it's calculated as `Int64`. I think given how easy it is to overflow for even smallish displacements, we should ensure displace_analytical always computes using floating point.
> Fix displace_analytical when alpha is an integer type

- Project.toml
- docs/src/api.md
- src/QuantumOpticsBase.jl
- src/superoperators.jl
- test/test_apply.jl
- test/test_superoperators.jl
`sprepost` is necessary for creating superoperators with different input and output hilbert space dimensions since `spre(A)*spost(B) != sprepost(A, B)` in such cases.
Note that I'm not sure exactly what the sensible behavior should be when calling `spre` or `spost` with an operator that doesn't have the same `basis_l` and `basis_r` and I've opened a relevant issue with qutip (https://github.com/qutip/qutip/issues/2171).
> Add sprepost to superoperators

- src/QuantumOpticsBase.jl
- src/superoperators.jl
- test/test_aqua.jl
- test/test_superoperators.jl
I'm not sure that I've implemented these in the right way as I'm still getting the hang of Julia's type system. So I'm opening this as a draft PR with the hope that maybe I can get some feedback on how I should actually implement these, as I am needing them for my research. My guess is that maybe superoperators need to have types similar to `DenseOpAdjType` and `SparseOpAdjType` implemented  so that adjoints can be done lazily?
> Add identitysuperoperator and dagger for SuperOperator

- Project.toml
- src/operators_dense.jl
- src/operators_sparse.jl
- src/superoperators.jl
- test/test_operators.jl
- test/test_superoperators.jl
I've found FastExpm to work quite well for creating the time evolution of certain, known to be sparse time evolution superoperators. For example
```julia
b = FockBasis(200)
L = liouvillian(identityoperator(b), [destroy(b)])
exp(L)
```
takes less then a second on my laptop. There's a relevant discussion here https://github.com/JuliaLang/julia/issues/32899 about upstream julia not wanting to implement sparse matrix exponential. However I think it makes sense to rely on FastExpm here since my guess is that most typcial Lindbladians can be computed efficiently by it.
> Use FastExpm.jl for matrix exponential of SparseSuperOperator

- src/apply.jl
- test/runtests.jl
- test/test_apply.jl
- test/test_time_dependent_operators.jl
`apply!` needs to be able to permute the operator based on the order of the indices of the qubits/subsystems, e.g., doing CNOT<sub>2->1</sub>. Resolves QuantumSavory/QuantumSavory.jl/issues/39 cc @Krastanov
> Make `apply!` work when used with any order of subsystem indices

- Project.toml
- src/apply.jl
- test/test_apply.jl
A previous pull request fixed a few issues with apply!, but there were still a number of edge cases that were not covered. This addresses such cases, simplifies the checks for whether an embedding is necessary, and properly detects permutations of the subsystem indices.
> Fixes and tests for `apply!`

- Project.toml
- src/QuantumOpticsBase.jl
- src/manybody.jl
- test/test_manybody.jl
This PR extends #157 by providing a more thought-out occupations interface. It also fixes the #102 issue, because the statistics is now stored in the occupations object.
To implement the occupations interface, one must implement these methods for the object:
- Ordering by defining `==` and `isless`
- Conversion from the occupations represented as a `Vector{Int}`, aka `convert(::Type{YourType}, v::AbstractVector)` so that `basisstate` could work normally
- `QuantumOpticsBase.state_transition!(buffer, occ, at_inds, a_inds)` for transition coefficients
- `similar` (if mutable) or `QuantumOpticsBase.allocate_buffer` (if immutable) for allocating a buffer
Maybe this should be documented for someone who needs, for example, [anyon statistics](https://en.wikipedia.org/wiki/Anyon) or extra …
> Occupations interface

- docs/src/api.md
- src/QuantumOpticsBase.jl
- src/charge.jl
- test/runtests.jl
- test/test_charge.jl
This basis is a truncated U(1) irrep basis intended to represent quantized charge. The charge operator is defined as are the conjugate (shift) operators `e^(ikφ)` associated with the U(1) degree of freedom φ.
Could do a minor version bump after this as we will export a bunch of new functions.
> Add a charge basis

- docs/src/api.md
- src/QuantumOpticsBase.jl
- src/time_dependent_operator.jl
`static_operator()` is useful for getting a non-lazy matrix representation of a time-dependent operator, for example in order to diagonalize it at a time `t`.
> Export and document `static_operator`

- Project.toml
- src/time_dependent_operator.jl
This is required to avoid allocs in set_time! with vector-backed TimeDependentSums.
Supports https://github.com/qojulia/QuantumOptics.jl/pull/401.
> Eliminate allocs in vector-based TimeDependentSums

- Project.toml
- src/operators_dense.jl
- src/states.jl
Part of https://github.com/QuantumSavory/QuantumSavory.jl/pull/143
> Solve piracies and ambiguities

- Project.toml
- src/QuantumOpticsBase.jl
- src/superoperators.jl
- test/test_superoperators.jl
- test/test_time_dependent_operators.jl
Unlike qutip, which uses `type = super, superrep = choi` to mark a `qobj` as a superoperator in the choi representation, I personally think it makes more sense to just reuse the normal `Operator` type to represent a choi matrix since it must be a valid density operator after all. Also it often makes sense to compute things like the Von Neumann entropy of the choi state. To convert back to the superoperator representation, one needs to assume some convention for which of the two Hilbert spaces is the auxiliary/reference/environment system and which represents the channel's output system. I've chosen the convention which seems standard to have the first system be the reference and the second be the output system.
I still need to add docs and tests but I thought I'd open this now as a draft …
> Create ChoiState type and conversions to/from SuperOperator

- Project.toml
- src/operators_lazytensor.jl
Currently, CUDA arrays cannot be used in lazy tensors due to unsafe views being used in the `mul!` implementation. This PR uses normal views instead, which after Julia 1.5 should be as performant as unsafeviews. Enabling Cuda arrays with LazyTensor could potentially help if the system is really huge and there is not enough memory to store the total matrix or allow for custom GPU kernels to be implemented (see [WaveguideQED.jl](https://github.com/qojulia/WaveguideQED.jl/tree/gpu) ). 
For a working minimal example where cuda arrays with LazyTensor ,see:
```julia
using QuantumOpticsBase
using CUDA
function to_gpu(a::Operator)
data = cu(map(ComplexF32,a.data))
gpu_operator = Operator(a.basis_l,a.basis_r,data)
return gpu_operator
end
function to_gpu(a::Ket)
data = cu(map(ComplexF32,a.data)) …
```
> Remove unsafeviews from LazyTensors

- src/printing.jl
See #45.
```
julia> create(FockBasis(2)) # before
Operator(dim=3x3)
basis: Fock(cutoff=2)sparse([2, 3], [1, 2], ComplexF64[1.0 + 0.0im, 1.4142135623730951 + 0.0im], 3, 3)
julia> create(FockBasis(2)) # after
Operator(dim=3x3)
basis: Fock(cutoff=2)
⋅                           ⋅            ⋅     
1.0 + 0.0im                      ⋅            ⋅     
⋅       1.4142135623730951 + 0.0im       ⋅    
julia> QuantumOpticsBase.set_printing(standard_order = true)
julia> create(FockBasis(2))
Operator(dim=3x3)
basis: Fock(cutoff=2)
[2, 1]  =  1.0+0.0im
[3, 2]  =  1.41421+0.0im
```
> Fix printing of `SparseOpPureType`

- src/operators_dense.jl
- src/operators_sparse.jl
- src/sparsematrix.jl
- src/superoperators.jl
The following microbenchmarks show that using `Base.PermutedDimsArray` over `_permutedims` gives an over 50x speedup for sparse arrays while still retaining the same performance for dense arrays. This means that the two separate implementations of `permutesystems` can be unified into one function.
```julia
using BenchmarkTools
using SparseArrays
function _permutedims(x::AbstractSparseMatrix, shape, perm)
shape = (shape...,)
shape_perm = ([shape[i] for i in perm]...,)
y = spzeros(eltype(x), x.m, x.n)
for I in eachindex(x)::CartesianIndices # Help with inference (detected by JET)
linear_index = LinearIndices((x.m, x.n))[I.I...]
cartesian_index = CartesianIndices(shape)[linear_index]
cartesian_index_perm = [cartesian_index[i] for i=perm]
linear_index_perm = …
```
> Remove `_permutedims` in favor of `Base.PermutedDimsArray`

- src/QuantumOpticsBase.jl
- src/nlevel.jl
- src/spin.jl
- test/test_nlevel.jl
> Add generalized pauli operators (aka clock and shift matrices)
